//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intranetMVC.WCFCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMatAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePatAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAluField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EscuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelAlumnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMatAlumno {
            get {
                return this.ApeMatAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMatAlumnoField, value) != true)) {
                    this.ApeMatAlumnoField = value;
                    this.RaisePropertyChanged("ApeMatAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePatAlumno {
            get {
                return this.ApePatAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePatAlumnoField, value) != true)) {
                    this.ApePatAlumnoField = value;
                    this.RaisePropertyChanged("ApePatAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAlu {
            get {
                return this.CodigoAluField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAluField, value) != true)) {
                    this.CodigoAluField = value;
                    this.RaisePropertyChanged("CodigoAlu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creditos {
            get {
                return this.CreditosField;
            }
            set {
                if ((this.CreditosField.Equals(value) != true)) {
                    this.CreditosField = value;
                    this.RaisePropertyChanged("Creditos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirAlumno {
            get {
                return this.DirAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.DirAlumnoField, value) != true)) {
                    this.DirAlumnoField = value;
                    this.RaisePropertyChanged("DirAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAlumno {
            get {
                return this.EmailAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAlumnoField, value) != true)) {
                    this.EmailAlumnoField = value;
                    this.RaisePropertyChanged("EmailAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Escuela {
            get {
                return this.EscuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.EscuelaField, value) != true)) {
                    this.EscuelaField = value;
                    this.RaisePropertyChanged("Escuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAlumno {
            get {
                return this.IdAlumnoField;
            }
            set {
                if ((this.IdAlumnoField.Equals(value) != true)) {
                    this.IdAlumnoField = value;
                    this.RaisePropertyChanged("IdAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomAlumno {
            get {
                return this.NomAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomAlumnoField, value) != true)) {
                    this.NomAlumnoField = value;
                    this.RaisePropertyChanged("NomAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelAlumno {
            get {
                return this.TelAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelAlumnoField, value) != true)) {
                    this.TelAlumnoField = value;
                    this.RaisePropertyChanged("TelAlumno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sala", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Sala : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int capacidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fecha_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idsalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rol_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_salaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ubicacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capacidad {
            get {
                return this.capacidadField;
            }
            set {
                if ((this.capacidadField.Equals(value) != true)) {
                    this.capacidadField = value;
                    this.RaisePropertyChanged("capacidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                if ((this.fecha_creacionField.Equals(value) != true)) {
                    this.fecha_creacionField = value;
                    this.RaisePropertyChanged("fecha_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idsala {
            get {
                return this.idsalaField;
            }
            set {
                if ((this.idsalaField.Equals(value) != true)) {
                    this.idsalaField = value;
                    this.RaisePropertyChanged("idsala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol_creacion {
            get {
                return this.rol_creacionField;
            }
            set {
                if ((object.ReferenceEquals(this.rol_creacionField, value) != true)) {
                    this.rol_creacionField = value;
                    this.RaisePropertyChanged("rol_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_sala {
            get {
                return this.tipo_salaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_salaField, value) != true)) {
                    this.tipo_salaField = value;
                    this.RaisePropertyChanged("tipo_sala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ubicacionField, value) != true)) {
                    this.ubicacionField = value;
                    this.RaisePropertyChanged("ubicacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cicloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idcursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mallaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrecursoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ciclo {
            get {
                return this.cicloField;
            }
            set {
                if ((this.cicloField.Equals(value) != true)) {
                    this.cicloField = value;
                    this.RaisePropertyChanged("ciclo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idcurso {
            get {
                return this.idcursoField;
            }
            set {
                if ((this.idcursoField.Equals(value) != true)) {
                    this.idcursoField = value;
                    this.RaisePropertyChanged("idcurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string malla {
            get {
                return this.mallaField;
            }
            set {
                if ((object.ReferenceEquals(this.mallaField, value) != true)) {
                    this.mallaField = value;
                    this.RaisePropertyChanged("malla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrecurso {
            get {
                return this.nombrecursoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrecursoField, value) != true)) {
                    this.nombrecursoField = value;
                    this.RaisePropertyChanged("nombrecurso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idsedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idsede {
            get {
                return this.idsedeField;
            }
            set {
                if ((this.idsedeField.Equals(value) != true)) {
                    this.idsedeField = value;
                    this.RaisePropertyChanged("idsede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asistencias", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Asistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idasistenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private intranetMVC.WCFCliente.ListaAsistencias[] listaAsistentesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idasistencias {
            get {
                return this.idasistenciasField;
            }
            set {
                if ((this.idasistenciasField.Equals(value) != true)) {
                    this.idasistenciasField = value;
                    this.RaisePropertyChanged("idasistencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public intranetMVC.WCFCliente.ListaAsistencias[] listaAsistentes {
            get {
                return this.listaAsistentesField;
            }
            set {
                if ((object.ReferenceEquals(this.listaAsistentesField, value) != true)) {
                    this.listaAsistentesField = value;
                    this.RaisePropertyChanged("listaAsistentes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaAsistencias", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class ListaAsistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ap_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ap_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idasistenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ap_materno {
            get {
                return this.ap_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ap_maternoField, value) != true)) {
                    this.ap_maternoField = value;
                    this.RaisePropertyChanged("ap_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ap_paterno {
            get {
                return this.ap_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ap_paternoField, value) != true)) {
                    this.ap_paternoField = value;
                    this.RaisePropertyChanged("ap_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idasistencias {
            get {
                return this.idasistenciasField;
            }
            set {
                if ((this.idasistenciasField.Equals(value) != true)) {
                    this.idasistenciasField = value;
                    this.RaisePropertyChanged("idasistencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participante", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Participante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ap_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ap_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idparticipanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_participanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ap_materno {
            get {
                return this.ap_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ap_maternoField, value) != true)) {
                    this.ap_maternoField = value;
                    this.RaisePropertyChanged("ap_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ap_paterno {
            get {
                return this.ap_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ap_paternoField, value) != true)) {
                    this.ap_paternoField = value;
                    this.RaisePropertyChanged("ap_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carrera {
            get {
                return this.carreraField;
            }
            set {
                if ((object.ReferenceEquals(this.carreraField, value) != true)) {
                    this.carreraField = value;
                    this.RaisePropertyChanged("carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idparticipante {
            get {
                return this.idparticipanteField;
            }
            set {
                if ((this.idparticipanteField.Equals(value) != true)) {
                    this.idparticipanteField = value;
                    this.RaisePropertyChanged("idparticipante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_participante {
            get {
                return this.tipo_participanteField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_participanteField, value) != true)) {
                    this.tipo_participanteField = value;
                    this.RaisePropertyChanged("tipo_participante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFCliente.IWCFIntranet")]
    public interface IWCFIntranet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoListar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoListarResponse")]
        intranetMVC.WCFCliente.Alumno[] AlumnoListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoListar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoListarResponse")]
        System.Threading.Tasks.Task<intranetMVC.WCFCliente.Alumno[]> AlumnoListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoAdicionarResponse")]
        void AlumnoAdicionar(intranetMVC.WCFCliente.Alumno emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoAdicionarResponse")]
        System.Threading.Tasks.Task AlumnoAdicionarAsync(intranetMVC.WCFCliente.Alumno emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoActualizar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoActualizarResponse")]
        void AlumnoActualizar(intranetMVC.WCFCliente.Alumno emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoActualizar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoActualizarResponse")]
        System.Threading.Tasks.Task AlumnoActualizarAsync(intranetMVC.WCFCliente.Alumno emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoEliminar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoEliminarResponse")]
        void AlumnoEliminar(int emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoEliminar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoEliminarResponse")]
        System.Threading.Tasks.Task AlumnoEliminarAsync(int emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoBuscar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoBuscarResponse")]
        intranetMVC.WCFCliente.Alumno AlumnoBuscar(int emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoBuscar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoBuscarResponse")]
        System.Threading.Tasks.Task<intranetMVC.WCFCliente.Alumno> AlumnoBuscarAsync(int emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SalaBuscarPorNombre", ReplyAction="http://tempuri.org/IWCFIntranet/SalaBuscarPorNombreResponse")]
        intranetMVC.WCFCliente.Sala SalaBuscarPorNombre(intranetMVC.WCFCliente.Sala pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SalaBuscarPorNombre", ReplyAction="http://tempuri.org/IWCFIntranet/SalaBuscarPorNombreResponse")]
        System.Threading.Tasks.Task<intranetMVC.WCFCliente.Sala> SalaBuscarPorNombreAsync(intranetMVC.WCFCliente.Sala pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/CursoListar", ReplyAction="http://tempuri.org/IWCFIntranet/CursoListarResponse")]
        intranetMVC.WCFCliente.Curso[] CursoListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/CursoListar", ReplyAction="http://tempuri.org/IWCFIntranet/CursoListarResponse")]
        System.Threading.Tasks.Task<intranetMVC.WCFCliente.Curso[]> CursoListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedesListar", ReplyAction="http://tempuri.org/IWCFIntranet/SedesListarResponse")]
        intranetMVC.WCFCliente.Sede[] SedesListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedesListar", ReplyAction="http://tempuri.org/IWCFIntranet/SedesListarResponse")]
        System.Threading.Tasks.Task<intranetMVC.WCFCliente.Sede[]> SedesListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeAdicionarResponse")]
        void SedeAdicionar(intranetMVC.WCFCliente.Sede sed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeAdicionarResponse")]
        System.Threading.Tasks.Task SedeAdicionarAsync(intranetMVC.WCFCliente.Sede sed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeActualizar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeActualizarResponse")]
        void SedeActualizar(intranetMVC.WCFCliente.Sede sed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeActualizar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeActualizarResponse")]
        System.Threading.Tasks.Task SedeActualizarAsync(intranetMVC.WCFCliente.Sede sed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeEliminar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeEliminarResponse")]
        void SedeEliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeEliminar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeEliminarResponse")]
        System.Threading.Tasks.Task SedeEliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeBuscar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeBuscarResponse")]
        intranetMVC.WCFCliente.Sede SedeBuscar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeBuscar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeBuscarResponse")]
        System.Threading.Tasks.Task<intranetMVC.WCFCliente.Sede> SedeBuscarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AsistenciaAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/AsistenciaAdicionarResponse")]
        void AsistenciaAdicionar(intranetMVC.WCFCliente.Asistencias emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AsistenciaAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/AsistenciaAdicionarResponse")]
        System.Threading.Tasks.Task AsistenciaAdicionarAsync(intranetMVC.WCFCliente.Asistencias emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteListar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteListarResponse")]
        intranetMVC.WCFCliente.Participante[] ParticipanteListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteListar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteListarResponse")]
        System.Threading.Tasks.Task<intranetMVC.WCFCliente.Participante[]> ParticipanteListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteAdicionarResponse")]
        void ParticipanteAdicionar(intranetMVC.WCFCliente.Participante emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteAdicionarResponse")]
        System.Threading.Tasks.Task ParticipanteAdicionarAsync(intranetMVC.WCFCliente.Participante emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteActualizar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteActualizarResponse")]
        void ParticipanteActualizar(intranetMVC.WCFCliente.Participante emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteActualizar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteActualizarResponse")]
        System.Threading.Tasks.Task ParticipanteActualizarAsync(intranetMVC.WCFCliente.Participante emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteEliminar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteEliminarResponse")]
        void ParticipanteEliminar(int emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteEliminar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteEliminarResponse")]
        System.Threading.Tasks.Task ParticipanteEliminarAsync(int emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteBuscar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteBuscarResponse")]
        intranetMVC.WCFCliente.Alumno ParticipanteBuscar(int emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteBuscar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteBuscarResponse")]
        System.Threading.Tasks.Task<intranetMVC.WCFCliente.Alumno> ParticipanteBuscarAsync(int emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/Validarusuario", ReplyAction="http://tempuri.org/IWCFIntranet/ValidarusuarioResponse")]
        bool Validarusuario(intranetMVC.WCFCliente.Usuario u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/Validarusuario", ReplyAction="http://tempuri.org/IWCFIntranet/ValidarusuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarusuarioAsync(intranetMVC.WCFCliente.Usuario u);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFIntranetChannel : intranetMVC.WCFCliente.IWCFIntranet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFIntranetClient : System.ServiceModel.ClientBase<intranetMVC.WCFCliente.IWCFIntranet>, intranetMVC.WCFCliente.IWCFIntranet {
        
        public WCFIntranetClient() {
        }
        
        public WCFIntranetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFIntranetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFIntranetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFIntranetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public intranetMVC.WCFCliente.Alumno[] AlumnoListar() {
            return base.Channel.AlumnoListar();
        }
        
        public System.Threading.Tasks.Task<intranetMVC.WCFCliente.Alumno[]> AlumnoListarAsync() {
            return base.Channel.AlumnoListarAsync();
        }
        
        public void AlumnoAdicionar(intranetMVC.WCFCliente.Alumno emp) {
            base.Channel.AlumnoAdicionar(emp);
        }
        
        public System.Threading.Tasks.Task AlumnoAdicionarAsync(intranetMVC.WCFCliente.Alumno emp) {
            return base.Channel.AlumnoAdicionarAsync(emp);
        }
        
        public void AlumnoActualizar(intranetMVC.WCFCliente.Alumno emp) {
            base.Channel.AlumnoActualizar(emp);
        }
        
        public System.Threading.Tasks.Task AlumnoActualizarAsync(intranetMVC.WCFCliente.Alumno emp) {
            return base.Channel.AlumnoActualizarAsync(emp);
        }
        
        public void AlumnoEliminar(int emp) {
            base.Channel.AlumnoEliminar(emp);
        }
        
        public System.Threading.Tasks.Task AlumnoEliminarAsync(int emp) {
            return base.Channel.AlumnoEliminarAsync(emp);
        }
        
        public intranetMVC.WCFCliente.Alumno AlumnoBuscar(int emp) {
            return base.Channel.AlumnoBuscar(emp);
        }
        
        public System.Threading.Tasks.Task<intranetMVC.WCFCliente.Alumno> AlumnoBuscarAsync(int emp) {
            return base.Channel.AlumnoBuscarAsync(emp);
        }
        
        public intranetMVC.WCFCliente.Sala SalaBuscarPorNombre(intranetMVC.WCFCliente.Sala pro) {
            return base.Channel.SalaBuscarPorNombre(pro);
        }
        
        public System.Threading.Tasks.Task<intranetMVC.WCFCliente.Sala> SalaBuscarPorNombreAsync(intranetMVC.WCFCliente.Sala pro) {
            return base.Channel.SalaBuscarPorNombreAsync(pro);
        }
        
        public intranetMVC.WCFCliente.Curso[] CursoListar() {
            return base.Channel.CursoListar();
        }
        
        public System.Threading.Tasks.Task<intranetMVC.WCFCliente.Curso[]> CursoListarAsync() {
            return base.Channel.CursoListarAsync();
        }
        
        public intranetMVC.WCFCliente.Sede[] SedesListar() {
            return base.Channel.SedesListar();
        }
        
        public System.Threading.Tasks.Task<intranetMVC.WCFCliente.Sede[]> SedesListarAsync() {
            return base.Channel.SedesListarAsync();
        }
        
        public void SedeAdicionar(intranetMVC.WCFCliente.Sede sed) {
            base.Channel.SedeAdicionar(sed);
        }
        
        public System.Threading.Tasks.Task SedeAdicionarAsync(intranetMVC.WCFCliente.Sede sed) {
            return base.Channel.SedeAdicionarAsync(sed);
        }
        
        public void SedeActualizar(intranetMVC.WCFCliente.Sede sed) {
            base.Channel.SedeActualizar(sed);
        }
        
        public System.Threading.Tasks.Task SedeActualizarAsync(intranetMVC.WCFCliente.Sede sed) {
            return base.Channel.SedeActualizarAsync(sed);
        }
        
        public void SedeEliminar(int id) {
            base.Channel.SedeEliminar(id);
        }
        
        public System.Threading.Tasks.Task SedeEliminarAsync(int id) {
            return base.Channel.SedeEliminarAsync(id);
        }
        
        public intranetMVC.WCFCliente.Sede SedeBuscar(int id) {
            return base.Channel.SedeBuscar(id);
        }
        
        public System.Threading.Tasks.Task<intranetMVC.WCFCliente.Sede> SedeBuscarAsync(int id) {
            return base.Channel.SedeBuscarAsync(id);
        }
        
        public void AsistenciaAdicionar(intranetMVC.WCFCliente.Asistencias emp) {
            base.Channel.AsistenciaAdicionar(emp);
        }
        
        public System.Threading.Tasks.Task AsistenciaAdicionarAsync(intranetMVC.WCFCliente.Asistencias emp) {
            return base.Channel.AsistenciaAdicionarAsync(emp);
        }
        
        public intranetMVC.WCFCliente.Participante[] ParticipanteListar() {
            return base.Channel.ParticipanteListar();
        }
        
        public System.Threading.Tasks.Task<intranetMVC.WCFCliente.Participante[]> ParticipanteListarAsync() {
            return base.Channel.ParticipanteListarAsync();
        }
        
        public void ParticipanteAdicionar(intranetMVC.WCFCliente.Participante emp) {
            base.Channel.ParticipanteAdicionar(emp);
        }
        
        public System.Threading.Tasks.Task ParticipanteAdicionarAsync(intranetMVC.WCFCliente.Participante emp) {
            return base.Channel.ParticipanteAdicionarAsync(emp);
        }
        
        public void ParticipanteActualizar(intranetMVC.WCFCliente.Participante emp) {
            base.Channel.ParticipanteActualizar(emp);
        }
        
        public System.Threading.Tasks.Task ParticipanteActualizarAsync(intranetMVC.WCFCliente.Participante emp) {
            return base.Channel.ParticipanteActualizarAsync(emp);
        }
        
        public void ParticipanteEliminar(int emp) {
            base.Channel.ParticipanteEliminar(emp);
        }
        
        public System.Threading.Tasks.Task ParticipanteEliminarAsync(int emp) {
            return base.Channel.ParticipanteEliminarAsync(emp);
        }
        
        public intranetMVC.WCFCliente.Alumno ParticipanteBuscar(int emp) {
            return base.Channel.ParticipanteBuscar(emp);
        }
        
        public System.Threading.Tasks.Task<intranetMVC.WCFCliente.Alumno> ParticipanteBuscarAsync(int emp) {
            return base.Channel.ParticipanteBuscarAsync(emp);
        }
        
        public bool Validarusuario(intranetMVC.WCFCliente.Usuario u) {
            return base.Channel.Validarusuario(u);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarusuarioAsync(intranetMVC.WCFCliente.Usuario u) {
            return base.Channel.ValidarusuarioAsync(u);
        }
    }
}
