//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intranetMVC.WCFCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePatAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMatAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAluField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirAlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarreraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAlumno {
            get {
                return this.IdAlumnoField;
            }
            set {
                if ((this.IdAlumnoField.Equals(value) != true)) {
                    this.IdAlumnoField = value;
                    this.RaisePropertyChanged("IdAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ApePatAlumno {
            get {
                return this.ApePatAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePatAlumnoField, value) != true)) {
                    this.ApePatAlumnoField = value;
                    this.RaisePropertyChanged("ApePatAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ApeMatAlumno {
            get {
                return this.ApeMatAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMatAlumnoField, value) != true)) {
                    this.ApeMatAlumnoField = value;
                    this.RaisePropertyChanged("ApeMatAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string NomAlumno {
            get {
                return this.NomAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomAlumnoField, value) != true)) {
                    this.NomAlumnoField = value;
                    this.RaisePropertyChanged("NomAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CodigoAlu {
            get {
                return this.CodigoAluField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAluField, value) != true)) {
                    this.CodigoAluField = value;
                    this.RaisePropertyChanged("CodigoAlu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string TelAlumno {
            get {
                return this.TelAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelAlumnoField, value) != true)) {
                    this.TelAlumnoField = value;
                    this.RaisePropertyChanged("TelAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public char Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string EmailAlumno {
            get {
                return this.EmailAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAlumnoField, value) != true)) {
                    this.EmailAlumnoField = value;
                    this.RaisePropertyChanged("EmailAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string DirAlumno {
            get {
                return this.DirAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.DirAlumnoField, value) != true)) {
                    this.DirAlumnoField = value;
                    this.RaisePropertyChanged("DirAlumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Carrera {
            get {
                return this.CarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CarreraField, value) != true)) {
                    this.CarreraField = value;
                    this.RaisePropertyChanged("Carrera");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idcursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char MallaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idclcloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTarifaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idcurso {
            get {
                return this.idcursoField;
            }
            set {
                if ((this.idcursoField.Equals(value) != true)) {
                    this.idcursoField = value;
                    this.RaisePropertyChanged("idcurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string NombreCurso {
            get {
                return this.NombreCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCursoField, value) != true)) {
                    this.NombreCursoField = value;
                    this.RaisePropertyChanged("NombreCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public char Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public char Malla {
            get {
                return this.MallaField;
            }
            set {
                if ((this.MallaField.Equals(value) != true)) {
                    this.MallaField = value;
                    this.RaisePropertyChanged("Malla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int idclclo {
            get {
                return this.idclcloField;
            }
            set {
                if ((this.idclcloField.Equals(value) != true)) {
                    this.idclcloField = value;
                    this.RaisePropertyChanged("idclclo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int idTarifa {
            get {
                return this.idTarifaField;
            }
            set {
                if ((this.idTarifaField.Equals(value) != true)) {
                    this.idTarifaField = value;
                    this.RaisePropertyChanged("idTarifa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField.Equals(value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asistencias", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Asistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idasistenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<intranetMVC.WCFCliente.ListaAsistencias> listaAsistentesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idasistencias {
            get {
                return this.idasistenciasField;
            }
            set {
                if ((this.idasistenciasField.Equals(value) != true)) {
                    this.idasistenciasField = value;
                    this.RaisePropertyChanged("idasistencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<intranetMVC.WCFCliente.ListaAsistencias> listaAsistentes {
            get {
                return this.listaAsistentesField;
            }
            set {
                if ((object.ReferenceEquals(this.listaAsistentesField, value) != true)) {
                    this.listaAsistentesField = value;
                    this.RaisePropertyChanged("listaAsistentes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaAsistencias", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class ListaAsistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ap_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ap_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idasistenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ap_materno {
            get {
                return this.ap_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ap_maternoField, value) != true)) {
                    this.ap_maternoField = value;
                    this.RaisePropertyChanged("ap_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ap_paterno {
            get {
                return this.ap_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ap_paternoField, value) != true)) {
                    this.ap_paternoField = value;
                    this.RaisePropertyChanged("ap_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idasistencias {
            get {
                return this.idasistenciasField;
            }
            set {
                if ((this.idasistenciasField.Equals(value) != true)) {
                    this.idasistenciasField = value;
                    this.RaisePropertyChanged("idasistencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participante", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Participante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ap_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ap_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idparticipanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_participanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ap_materno {
            get {
                return this.ap_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ap_maternoField, value) != true)) {
                    this.ap_maternoField = value;
                    this.RaisePropertyChanged("ap_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ap_paterno {
            get {
                return this.ap_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ap_paternoField, value) != true)) {
                    this.ap_paternoField = value;
                    this.RaisePropertyChanged("ap_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carrera {
            get {
                return this.carreraField;
            }
            set {
                if ((object.ReferenceEquals(this.carreraField, value) != true)) {
                    this.carreraField = value;
                    this.RaisePropertyChanged("carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idparticipante {
            get {
                return this.idparticipanteField;
            }
            set {
                if ((this.idparticipanteField.Equals(value) != true)) {
                    this.idparticipanteField = value;
                    this.RaisePropertyChanged("idparticipante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo_participante {
            get {
                return this.tipo_participanteField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_participanteField, value) != true)) {
                    this.tipo_participanteField = value;
                    this.RaisePropertyChanged("tipo_participante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/intranet.entity")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFCliente.IWCFIntranet")]
    public interface IWCFIntranet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoListar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoListarResponse")]
        intranetMVC.WCFCliente.AlumnoListarResponse AlumnoListar(intranetMVC.WCFCliente.AlumnoListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoAdicionarResponse")]
        intranetMVC.WCFCliente.AlumnoAdicionarResponse AlumnoAdicionar(intranetMVC.WCFCliente.AlumnoAdicionarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoActualizar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoActualizarResponse")]
        intranetMVC.WCFCliente.AlumnoActualizarResponse AlumnoActualizar(intranetMVC.WCFCliente.AlumnoActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoEliminar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoEliminarResponse")]
        intranetMVC.WCFCliente.AlumnoEliminarResponse AlumnoEliminar(intranetMVC.WCFCliente.AlumnoEliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AlumnoBuscar", ReplyAction="http://tempuri.org/IWCFIntranet/AlumnoBuscarResponse")]
        intranetMVC.WCFCliente.AlumnoBuscarResponse AlumnoBuscar(intranetMVC.WCFCliente.AlumnoBuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/CursoListar", ReplyAction="http://tempuri.org/IWCFIntranet/CursoListarResponse")]
        intranetMVC.WCFCliente.CursoListarResponse CursoListar(intranetMVC.WCFCliente.CursoListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedesListar", ReplyAction="http://tempuri.org/IWCFIntranet/SedesListarResponse")]
        intranetMVC.WCFCliente.SedesListarResponse SedesListar(intranetMVC.WCFCliente.SedesListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeAdicionarResponse")]
        intranetMVC.WCFCliente.SedeAdicionarResponse SedeAdicionar(intranetMVC.WCFCliente.SedeAdicionarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeActualizar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeActualizarResponse")]
        intranetMVC.WCFCliente.SedeActualizarResponse SedeActualizar(intranetMVC.WCFCliente.SedeActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeEliminar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeEliminarResponse")]
        intranetMVC.WCFCliente.SedeEliminarResponse SedeEliminar(intranetMVC.WCFCliente.SedeEliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/SedeBuscar", ReplyAction="http://tempuri.org/IWCFIntranet/SedeBuscarResponse")]
        intranetMVC.WCFCliente.SedeBuscarResponse SedeBuscar(intranetMVC.WCFCliente.SedeBuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/AsistenciaAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/AsistenciaAdicionarResponse")]
        intranetMVC.WCFCliente.AsistenciaAdicionarResponse AsistenciaAdicionar(intranetMVC.WCFCliente.AsistenciaAdicionarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteListar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteListarResponse")]
        intranetMVC.WCFCliente.ParticipanteListarResponse ParticipanteListar(intranetMVC.WCFCliente.ParticipanteListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteAdicionar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteAdicionarResponse")]
        intranetMVC.WCFCliente.ParticipanteAdicionarResponse ParticipanteAdicionar(intranetMVC.WCFCliente.ParticipanteAdicionarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteActualizar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteActualizarResponse")]
        intranetMVC.WCFCliente.ParticipanteActualizarResponse ParticipanteActualizar(intranetMVC.WCFCliente.ParticipanteActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteEliminar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteEliminarResponse")]
        intranetMVC.WCFCliente.ParticipanteEliminarResponse ParticipanteEliminar(intranetMVC.WCFCliente.ParticipanteEliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/ParticipanteBuscar", ReplyAction="http://tempuri.org/IWCFIntranet/ParticipanteBuscarResponse")]
        intranetMVC.WCFCliente.ParticipanteBuscarResponse ParticipanteBuscar(intranetMVC.WCFCliente.ParticipanteBuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFIntranet/Validarusuario", ReplyAction="http://tempuri.org/IWCFIntranet/ValidarusuarioResponse")]
        intranetMVC.WCFCliente.ValidarusuarioResponse Validarusuario(intranetMVC.WCFCliente.ValidarusuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoListar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoListarRequest {
        
        public AlumnoListarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoListarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<intranetMVC.WCFCliente.Alumno> AlumnoListarResult;
        
        public AlumnoListarResponse() {
        }
        
        public AlumnoListarResponse(System.Collections.Generic.List<intranetMVC.WCFCliente.Alumno> AlumnoListarResult) {
            this.AlumnoListarResult = AlumnoListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoAdicionar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoAdicionarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Alumno emp;
        
        public AlumnoAdicionarRequest() {
        }
        
        public AlumnoAdicionarRequest(intranetMVC.WCFCliente.Alumno emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoAdicionarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoAdicionarResponse {
        
        public AlumnoAdicionarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoActualizar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Alumno emp;
        
        public AlumnoActualizarRequest() {
        }
        
        public AlumnoActualizarRequest(intranetMVC.WCFCliente.Alumno emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoActualizarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoActualizarResponse {
        
        public AlumnoActualizarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoEliminar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoEliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int emp;
        
        public AlumnoEliminarRequest() {
        }
        
        public AlumnoEliminarRequest(int emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoEliminarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoEliminarResponse {
        
        public AlumnoEliminarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoBuscar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoBuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int emp;
        
        public AlumnoBuscarRequest() {
        }
        
        public AlumnoBuscarRequest(int emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AlumnoBuscarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AlumnoBuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Alumno AlumnoBuscarResult;
        
        public AlumnoBuscarResponse() {
        }
        
        public AlumnoBuscarResponse(intranetMVC.WCFCliente.Alumno AlumnoBuscarResult) {
            this.AlumnoBuscarResult = AlumnoBuscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CursoListar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CursoListarRequest {
        
        public CursoListarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CursoListarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CursoListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<intranetMVC.WCFCliente.Curso> CursoListarResult;
        
        public CursoListarResponse() {
        }
        
        public CursoListarResponse(System.Collections.Generic.List<intranetMVC.WCFCliente.Curso> CursoListarResult) {
            this.CursoListarResult = CursoListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedesListar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedesListarRequest {
        
        public SedesListarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedesListarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedesListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<intranetMVC.WCFCliente.Sede> SedesListarResult;
        
        public SedesListarResponse() {
        }
        
        public SedesListarResponse(System.Collections.Generic.List<intranetMVC.WCFCliente.Sede> SedesListarResult) {
            this.SedesListarResult = SedesListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedeAdicionar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedeAdicionarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Sede sed;
        
        public SedeAdicionarRequest() {
        }
        
        public SedeAdicionarRequest(intranetMVC.WCFCliente.Sede sed) {
            this.sed = sed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedeAdicionarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedeAdicionarResponse {
        
        public SedeAdicionarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedeActualizar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedeActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Sede sed;
        
        public SedeActualizarRequest() {
        }
        
        public SedeActualizarRequest(intranetMVC.WCFCliente.Sede sed) {
            this.sed = sed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedeActualizarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedeActualizarResponse {
        
        public SedeActualizarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedeEliminar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedeEliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public SedeEliminarRequest() {
        }
        
        public SedeEliminarRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedeEliminarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedeEliminarResponse {
        
        public SedeEliminarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedeBuscar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedeBuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public SedeBuscarRequest() {
        }
        
        public SedeBuscarRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SedeBuscarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SedeBuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Sede SedeBuscarResult;
        
        public SedeBuscarResponse() {
        }
        
        public SedeBuscarResponse(intranetMVC.WCFCliente.Sede SedeBuscarResult) {
            this.SedeBuscarResult = SedeBuscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AsistenciaAdicionar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AsistenciaAdicionarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Asistencias emp;
        
        public AsistenciaAdicionarRequest() {
        }
        
        public AsistenciaAdicionarRequest(intranetMVC.WCFCliente.Asistencias emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AsistenciaAdicionarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AsistenciaAdicionarResponse {
        
        public AsistenciaAdicionarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteListar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteListarRequest {
        
        public ParticipanteListarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteListarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<intranetMVC.WCFCliente.Participante> ParticipanteListarResult;
        
        public ParticipanteListarResponse() {
        }
        
        public ParticipanteListarResponse(System.Collections.Generic.List<intranetMVC.WCFCliente.Participante> ParticipanteListarResult) {
            this.ParticipanteListarResult = ParticipanteListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteAdicionar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteAdicionarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Participante emp;
        
        public ParticipanteAdicionarRequest() {
        }
        
        public ParticipanteAdicionarRequest(intranetMVC.WCFCliente.Participante emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteAdicionarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteAdicionarResponse {
        
        public ParticipanteAdicionarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteActualizar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Participante emp;
        
        public ParticipanteActualizarRequest() {
        }
        
        public ParticipanteActualizarRequest(intranetMVC.WCFCliente.Participante emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteActualizarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteActualizarResponse {
        
        public ParticipanteActualizarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteEliminar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteEliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int emp;
        
        public ParticipanteEliminarRequest() {
        }
        
        public ParticipanteEliminarRequest(int emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteEliminarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteEliminarResponse {
        
        public ParticipanteEliminarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteBuscar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteBuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int emp;
        
        public ParticipanteBuscarRequest() {
        }
        
        public ParticipanteBuscarRequest(int emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ParticipanteBuscarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ParticipanteBuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Alumno ParticipanteBuscarResult;
        
        public ParticipanteBuscarResponse() {
        }
        
        public ParticipanteBuscarResponse(intranetMVC.WCFCliente.Alumno ParticipanteBuscarResult) {
            this.ParticipanteBuscarResult = ParticipanteBuscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Validarusuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarusuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public intranetMVC.WCFCliente.Usuario u;
        
        public ValidarusuarioRequest() {
        }
        
        public ValidarusuarioRequest(intranetMVC.WCFCliente.Usuario u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarusuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarusuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ValidarusuarioResult;
        
        public ValidarusuarioResponse() {
        }
        
        public ValidarusuarioResponse(bool ValidarusuarioResult) {
            this.ValidarusuarioResult = ValidarusuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFIntranetChannel : intranetMVC.WCFCliente.IWCFIntranet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFIntranetClient : System.ServiceModel.ClientBase<intranetMVC.WCFCliente.IWCFIntranet>, intranetMVC.WCFCliente.IWCFIntranet {
        
        public WCFIntranetClient() {
        }
        
        public WCFIntranetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFIntranetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFIntranetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFIntranetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public intranetMVC.WCFCliente.AlumnoListarResponse AlumnoListar(intranetMVC.WCFCliente.AlumnoListarRequest request) {
            return base.Channel.AlumnoListar(request);
        }
        
        public intranetMVC.WCFCliente.AlumnoAdicionarResponse AlumnoAdicionar(intranetMVC.WCFCliente.AlumnoAdicionarRequest request) {
            return base.Channel.AlumnoAdicionar(request);
        }
        
        public intranetMVC.WCFCliente.AlumnoActualizarResponse AlumnoActualizar(intranetMVC.WCFCliente.AlumnoActualizarRequest request) {
            return base.Channel.AlumnoActualizar(request);
        }
        
        public intranetMVC.WCFCliente.AlumnoEliminarResponse AlumnoEliminar(intranetMVC.WCFCliente.AlumnoEliminarRequest request) {
            return base.Channel.AlumnoEliminar(request);
        }
        
        public intranetMVC.WCFCliente.AlumnoBuscarResponse AlumnoBuscar(intranetMVC.WCFCliente.AlumnoBuscarRequest request) {
            return base.Channel.AlumnoBuscar(request);
        }
        
        public intranetMVC.WCFCliente.CursoListarResponse CursoListar(intranetMVC.WCFCliente.CursoListarRequest request) {
            return base.Channel.CursoListar(request);
        }
        
        public intranetMVC.WCFCliente.SedesListarResponse SedesListar(intranetMVC.WCFCliente.SedesListarRequest request) {
            return base.Channel.SedesListar(request);
        }
        
        public intranetMVC.WCFCliente.SedeAdicionarResponse SedeAdicionar(intranetMVC.WCFCliente.SedeAdicionarRequest request) {
            return base.Channel.SedeAdicionar(request);
        }
        
        public intranetMVC.WCFCliente.SedeActualizarResponse SedeActualizar(intranetMVC.WCFCliente.SedeActualizarRequest request) {
            return base.Channel.SedeActualizar(request);
        }
        
        public intranetMVC.WCFCliente.SedeEliminarResponse SedeEliminar(intranetMVC.WCFCliente.SedeEliminarRequest request) {
            return base.Channel.SedeEliminar(request);
        }
        
        public intranetMVC.WCFCliente.SedeBuscarResponse SedeBuscar(intranetMVC.WCFCliente.SedeBuscarRequest request) {
            return base.Channel.SedeBuscar(request);
        }
        
        public intranetMVC.WCFCliente.AsistenciaAdicionarResponse AsistenciaAdicionar(intranetMVC.WCFCliente.AsistenciaAdicionarRequest request) {
            return base.Channel.AsistenciaAdicionar(request);
        }
        
        public intranetMVC.WCFCliente.ParticipanteListarResponse ParticipanteListar(intranetMVC.WCFCliente.ParticipanteListarRequest request) {
            return base.Channel.ParticipanteListar(request);
        }
        
        public intranetMVC.WCFCliente.ParticipanteAdicionarResponse ParticipanteAdicionar(intranetMVC.WCFCliente.ParticipanteAdicionarRequest request) {
            return base.Channel.ParticipanteAdicionar(request);
        }
        
        public intranetMVC.WCFCliente.ParticipanteActualizarResponse ParticipanteActualizar(intranetMVC.WCFCliente.ParticipanteActualizarRequest request) {
            return base.Channel.ParticipanteActualizar(request);
        }
        
        public intranetMVC.WCFCliente.ParticipanteEliminarResponse ParticipanteEliminar(intranetMVC.WCFCliente.ParticipanteEliminarRequest request) {
            return base.Channel.ParticipanteEliminar(request);
        }
        
        public intranetMVC.WCFCliente.ParticipanteBuscarResponse ParticipanteBuscar(intranetMVC.WCFCliente.ParticipanteBuscarRequest request) {
            return base.Channel.ParticipanteBuscar(request);
        }
        
        public intranetMVC.WCFCliente.ValidarusuarioResponse Validarusuario(intranetMVC.WCFCliente.ValidarusuarioRequest request) {
            return base.Channel.Validarusuario(request);
        }
    }
}
